### ISSUE TITLE
La barra de busqueda no es funcional

### ISSUE THREAD

**Issue by TheMishi99** [VeronicaBianchi/mercadoLiebreRender#1]
- 7 - No cumple porque es un bloque con texto dentro.

![image](https://github.com/VeronicaBianchi/mercadoLiebreRender/assets/119746498/be78ad30-dd88-4937-954e-dcecaca3a07a)

- 9 - Está todo perfecto.

- 10 - Considero que cumple con todo lo solicitado a excepción de la barra de búsqueda.

**Comment by VeronicaBianchi** [comment]
Buenass corrección de Issues realizada.
