### ISSUE TITLE
Revición pagina

### ISSUE THREAD

**Issue by Ramiro125** [VeronicaBianchi/mercadoLiebreRender#2]
- [x] 1 - Cumple con todo lo propuesto.

- [x] 2 - Cumple con todo lo propuesto.

- [x] 3 - Cumple con todo lo propuesto.

- [x] 4 - Cumple con todo lo propuesto.

- [x] 5 - Cumple con todo lo propuesto.

- [x] 6 - Cumple con todo lo propuesto.

- [ ] 7 - No cumple pero es un error simple.

- [x] 8 - Cumple con lo propuesto.

- [x] 9 - Me gusto mucho como tiene diseñado la pagina como combina todo y se armoniza, la verdad muy buen mercado liebre. Felicidades.

- [x] 10 - Solo mejorar el buscador.

**Comment by VeronicaBianchi** [comment]
Buen día corrección de Issues realizada.
